---
name: 1seasonvar.ru
stop_on_failure: true
retry_on_failure: true
initial_variables:
  TestedHostname: 1seasonvar.ru
env_variables:
  - APITEST_TELEGRAM_CHATID
  - APITEST_TELEGRAM_TOKEN
steps:
  - note: Checking health status
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/healthz
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_text
        comparison: equal
        value: ok
  - note: Taking source meta data for checking
    step_type: request
    method: GET
    url: http://seasonvar.ru/serial-4426-TCar__gori-1-season.html
    variables:
      - source: response_html
        property: .//title
        name: PageTitle
      - source: response_html
        property: .//meta[@name='keywords']/@content
        name: PageKeywords
      - source: response_html
        property: .//meta[@name='description']/@content
        name: PageDescription
    assertions:
      - source: response_status
        comparison: equal
        value: 200
  - note: Checking meta data
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/serial-4426-TCar__gori-1-season.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_html
        property: .//title
        comparison: equal
        value: "{{.PageTitle}}"
      - source: response_html
        property: .//meta[@name='keywords']/@content
        comparison: equal
        value: "{{.PageKeywords}}"
      - source: response_html
        property: .//meta[@name='description']/@content
        comparison: equal
        value: "{{.PageDescription}}"
  - note: Checking enabled HD button and hostname replace
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/tpl/asset/js/pg.player.min.js
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_text
        comparison: contains
        value: swichHD
      - source: response_text
        comparison: does_not_contain
        value: http://seasonvar.ru
  - note: Checking api/all_seasons result from first season link
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/api/all_seasons?url=%2Fserial-13911-Zavuchi-0001-sezon.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: "#"
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: 0.title
        comparison: contains
        value: Vice Principals 1
      - source: response_json
        property: 0.link
        comparison: equal
        value: /serial-13911-Zavuchi-0001-sezon.html
  - note: Checking api/all_seasons result from non-first season link
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/api/all_seasons?url=%2Fserial-14003-Amerikanskaya_istoriya_uzhasov-0006-sezon.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: "#"
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: 0.title
        comparison: contains
        value: American Horror Story 1
      - source: response_json
        property: 0.link
        comparison: equal
        value: /serial-3243-Amerikanskaja_istorija_uzhasov-1-season.html
  - note: Checking api/info_season result
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/api/info_season?url=%2Fserial-4426-TCar__gori-1-season.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: title
        comparison: has_key
      - source: response_json
        property: keywords
        comparison: has_key
      - source: response_json
        property: description
        comparison: has_key
      - source: response_json
        property: id
        comparison: equal
        value: 4426
      - source: response_json
        property: serial
        comparison: equal
        value: 2211
  - note: Checking api/all_series result
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/api/all_series?url=%2Fserial-4426-TCar__gori-1-season.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: "#"
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: 0.playlist.#
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: 0.playlist.0.id
        comparison: has_key
      - source: response_json
        property: 0.playlist.0.title
        comparison: has_key
      - source: response_json
        property: 0.playlist.0.file
        comparison: has_key
      - source: response_json
        property: 0.playlist.0.galabel
        comparison: has_key
  - note: Checking search result
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/autocomplete.php?query=house
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: query
        comparison: equal
        value: house
      - source: response_json
        property: suggestions.valu
        comparison: has_key
      - source: response_json
        property: suggestions.valu.#
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: suggestions.valu.0
        comparison: contains
        value: HOUSE M.D
      - source: response_json
        property: data.#
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: data.0
        comparison: contains
        value: season.html
      - source: response_json
        property: id.0
        comparison: is_a_number
  - note: Checking serial page
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/serial-12-Doktor_Haus-1-season.html
    assertions:
      - source: response_status
        comparison: equal
        value: 200
  - note: Checking playlist from seasonvar player (array)
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/playls2/08/trans/16626/plist.txt
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: "#"
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: 0.id
        comparison: has_key
      - source: response_json
        property: 0.title
        comparison: has_key
      - source: response_json
        property: 0.file
        comparison: has_key
      - source: response_json
        property: 0.galabel
        comparison: has_key
  - note: Checking playlist from seasonvar player
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/playls2/08/trans/16626/list.xml
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: name
        comparison: has_key
      - source: response_json
        property: playlist
        comparison: has_key
      - source: response_json
        property: playlist.#
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: playlist.0.comment
        comparison: has_key
      - source: response_json
        property: playlist.0.streamsend
        comparison: has_key
      - source: response_json
        property: playlist.0.file
        comparison: has_key
      - source: response_json
        property: playlist.0.galabel
        comparison: has_key
  - note: Checking robots.txt
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/robots.txt
    assertions:
      - source: response_status
        comparison: equal
        value: 200
  - note: Checking sitemap.xml
    step_type: request
    method: GET
    url: http://{{.TestedHostname}}/sitemap.xml
    assertions:
      - source: response_status
        comparison: equal
        value: 200
  - note: Checking datalock player
    step_type: request
    method: GET
    url: http://datalock.ru/player/1
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_headers
        property: Access-Control-Allow-Origin
        comparison: equal
        value: "*"
      - source: response_text
        comparison: contains
        value: htmlPlayer
      - source: response_text
        comparison: contains
        value: ;eval(function(y,t,u,p){var lIll=0;var ll1I=0;var Il1l=0;var ll1l=[];var l1lI=[];
  - note: Checking playlist from datalock player
    step_type: request
    method: GET
    url: http://datalock.ru/playlist/4f6e5fae1fc6898e4d7ac9335940a334/1/list.xml
    assertions:
      - source: response_status
        comparison: equal
        value: 200
      - source: response_json
        property: playlist.#
        comparison: is_greater_than
        value: 0
      - source: response_json
        property: playlist.0.comment
        comparison: has_key
      - source: response_json
        property: playlist.0.comment
        comparison: contains
        value: RenTV
      - source: response_json
        property: playlist.0.streamsend
        comparison: equal
        value: sec
      - source: response_json
        property: playlist.0.galabel
        comparison: has_key
      - source: response_json
        property: playlist.0.file
        comparison: has_key
      - source: response_json
        property: playlist.0.file
        comparison: contains
        value: 4f6e5fae1fc6898e4d7ac9335940a334
      - source: response_json
        property: playlist.0.file
        comparison: contains
        value: 7f_
  - note: Checking playlist with incorrect secureMark
    step_type: request
    method: GET
    url: http://datalock.ru/playlist/0/1/list.xml
    variables:
      - source: response_json
        property: playlist.0.file
        name: PlaylistFile
    assertions:
      - source: response_status
        comparison: equal
        value: 200
  - note: Checking access for movie file with incorrect secureMark
    step_type: request
    method: HEAD
    url: "{{.PlaylistFile}}"
    assertions:
      - source: response_status
        comparison: equal
        value: 200
notification:
  telegram:
    chat_id: "{{.APITEST_TELEGRAM_CHATID}}"
    token: "{{.APITEST_TELEGRAM_TOKEN}}"
